



import { Inter } from "next/font/google";
import "./globals.css";
import Provider, { useAppContext } from "./context/usercontext";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const {name}=useAppContext()
  return (
    <html lang="en">
      <body >

      
        <h1>wala layoutttttttttttttttttttttttt</h1>

        
        <Provider>

        
      
        <div style={{border:"2px solid red"}}>
        {children}
        </div>
        </Provider>
       
        
        </body>
    </html>
  );
}




